version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: sorgrao-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DATABASE:-sorgrao}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sorgrao-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sorgrao-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE:-sorgrao}
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME:-1d}
    networks:
      - sorgrao-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sorgrao-frontend
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    networks:
      - sorgrao-network

networks:
  sorgrao-network:
    driver: bridge

volumes:
  postgres_data:
